version: '3'

services: 
  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle-xe
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_PASSWORD=oracle